module.exports =  { 
  i18n: {
    locales: ['vi', 'ja'],
    defaultLocale: 'vi',
  },
  reactStrictMode: true,
  generateBuildId: async () => {
    // You can, for example, get the latest git commit hash here
    return 'songhongscr-app'
  },
  async rewrites() {
    return [
      {
        source : `/vi/${process.env.ABOUT_US_VI}`,
        destination : '/about',
        locale: false,
      },
      {
        source : `/ja/${process.env.ABOUT_US_JA}`,
        destination : '/about',
        locale: false,
      },
      {
        source : `/vi/${process.env.CONTACT_VI}`,
        destination : '/contact',
        locale: false,
      },
      {
        source : `/ja/${process.env.CONTACT_JA}`,
        destination : '/contact',
        locale: false,
      },
      {
        source : `/vi/${process.env.SERVICES_TAX_REWRITE}/:slug`,
        destination : '/services/category/:slug',
        locale: false,
      },
      {
        source : `/ja/${process.env.SERVICES_TAX_REWRITE}/:slug`,
        destination : '/services/category/:slug',
        locale: false,
      },
      {
        source : `/vi/${process.env.BANG_GIA_VI}/:slug`,
        destination : `/bang-gia/:slug`,
        locale: false,
      },
      {
        source : `/ja/${process.env.BANG_GIA_JA}/:slug`,
        destination : '/bang-gia/:slug',
        locale: false,
      },
      {
        source : `/vi/${process.env.QA_VI}`,
        destination : `/qa`,
        locale: false,
      },
      {
        source : `/ja/${process.env.QA_JA}`,
        destination : '/qa',
        locale: false,
      },
      {
        source : `/vi/${process.env.SERVICES_POST_TYPE}/:slug`,
        destination : `/services/single/:slug`,
        locale: false,
      },
      {
        source : `/ja/${process.env.SERVICES_POST_TYPE}/:slug`,
        destination : '/services/single/:slug',
        locale: false,
      },
      {
        source : `/vi/${process.env.NEWS_TAX_REWRITE}/:slug`,
        destination : `/tin-tuc/category/:slug`,
        locale: false,
      },
      {
        source : `/ja/${process.env.NEWS_TAX_REWRITE}/:slug`,
        destination : '/tin-tuc/category/:slug',
        locale: false,
      },
      {
        source : `/vi/${process.env.HDXH_VI}`,
        destination : `/hoat-dong-xa-hoi`,
        locale: false,
      },
      {
        source : `/ja/${process.env.HDXH_JA}`,
        destination : '/hoat-dong-xa-hoi',
        locale: false,
      },
      {
        source : `/vi/${process.env.HDXH_POST_TYPE}/:slug`,
        destination : `/hdxh/:slug`,
        locale: false,
      },
      {
        source : `/ja/${process.env.HDXH_POST_TYPE}/:slug`,
        destination : '/hdxh/:slug',
        locale: false,
      },
      {
        source : `/vi/${process.env.TINH_TIEN_NENKINS_THUE_VI}/${process.env.TINH_TIEN_NENKINS_VI}`,
        destination : `/tinh-tien/nenkins`,
        locale: false,
      },
      {
        source : `/ja/${process.env.TINH_TIEN_NENKINS_THUE_JA}/${process.env.TINH_TIEN_NENKINS_JA}`,
        destination : '/tinh-tien/nenkins',
        locale: false,
      },
      {
        source : `/vi/${process.env.TINH_TIEN_NENKINS_THUE_VI}/${process.env.TINH_TIEN_HOANTHUE_VI}`,
        destination : `/tinh-tien/hoan-thue`,
        locale: false,
      },
      {
        source : `/ja/${process.env.TINH_TIEN_NENKINS_THUE_JA}/${process.env.TINH_TIEN_HOANTHUE_JA}`,
        destination : '/tinh-tien/hoan-thue',
        locale: false,
      },
      {
        source : `/vi/${process.env.DANG_NHAP_VI}`,
        destination : `/dang-nhap`,
        locale: false,
      },
      {
        source : `/ja/${process.env.DANG_NHAP_JA}`,
        destination : '/dang-nhap',
        locale: false,
      },
      {
        source : `/vi/${process.env.DANG_KY_VI}`,
        destination : `/dang-ky`,
        locale: false,
      },
      {
        source : `/ja/${process.env.DANG_KY_JA}`,
        destination : '/dang-ky',
        locale: false,
      },
      {
        source : `/vi/${process.env.ACCOUNT_VI}/:slug`,
        destination : `/account/:slug`,
        locale: false,
      },
      {
        source : `/ja/${process.env.ACCOUNT_JA}/:slug`,
        destination : `/account/:slug`,
        locale: false,
      },
      {
        source : `/vi/${process.env.QUEN_MAT_KHAU_VI}`,
        destination : `/quen-mat-khau`,
        locale: false,
      },
      {
        source : `/ja/${process.env.QUEN_MAT_KHAU_JA}`,
        destination : '/quen-mat-khau',
        locale: false,
      },
      {
        source : `/vi/${process.env.RESET_MAT_KHAU_VI}`,
        destination : `/reset-mat-khau`,
        locale: false,
      },
      {
        source : `/ja/${process.env.RESET_MAT_KHAU_JA}`,
        destination : '/reset-mat-khau',
        locale: false,
      },
      {
        source : `/vi/${process.env.SEARCH_VI}`,
        destination : `/search`,
        locale: false,
      },
      {
        source : `/ja/${process.env.SEARCH_JA}`,
        destination : '/search',
        locale: false,
      },
      {
        source : `/vi/xac-nhan-tien/:slug`,
        destination : '/confirms/:slug',
        locale: false,
      },
      {
        source : `/ja/xac-nhan-tien/:slug`,
        destination : '/confirms/:slug',
        locale: false,
      },
      {
        source : `/vi/:slug`,
        destination : `/middleware/:slug`,
        locale: false,
      },
      {
        source : `/ja/:slug`,
        destination : '/middleware/:slug',
        locale: false,
      }
    ]
  },
  images: {
    domains: [process.env.WP_SITE_DOMAIN],
  },
  env: {
    WP_SITE_DOMAIN: process.env.WP_SITE_DOMAIN,
    WP_SITE_URL: process.env.WP_SITE_URL,
    WP_API_URL: process.env.WP_API_URL,
    WP_RANKMATH_API_URL: process.env.WP_RANKMATH_API_URL,
    ABOUT_US_VI: process.env.ABOUT_US_VI,
    ABOUT_US_JA: process.env.ABOUT_US_JA,
    BANG_GIA_VI: process.env.BANG_GIA_VI,
    BANG_GIA_JA: process.env.BANG_GIA_JA,
    NENKINS_VI: process.env.NENKINS_VI,
    NENKINS_JA: process.env.NENKINS_JA,
    HOANTHUE_VI: process.env.HOANTHUE_VI,
    HOANTHUE_JA: process.env.HOANTHUE_JA,
    BIENPHIENDICH_VI: process.env.BIENPHIENDICH_VI,
    BIENPHIENDICH_JA: process.env.BIENPHIENDICH_JA,
    VISATUCACHLUUTRU_VI: process.env.VISATUCACHLUUTRU_VI,
    VISATUCACHLUUTRU_JA: process.env.VISATUCACHLUUTRU_JA,
    SERVICES_TAX_REWRITE: process.env.SERVICES_TAX_REWRITE,
    SERVICES_TAX: process.env.SERVICES_TAX,
    NENKIN_TERM_VI: process.env.NENKIN_TERM_VI,
    NENKIN_TERM_JA: process.env.NENKIN_TERM_JA,
    QA_VI: process.env.QA_VI,
    QA_JA: process.env.QA_JA,
    CONTACT_VI: process.env.CONTACT_VI,
    CONTACT_JA: process.env.CONTACT_JA,
    SERVICES_VI: process.env.SERVICES_VI,
    SERVICES_JA: process.env.SERVICES_JA,
    SERVICES_POST_TYPE: process.env.SERVICES_POST_TYPE,
    NEWS_POST_TYPE: process.env.NEWS_POST_TYPE,
    NEWS_TAX_REWRITE: process.env.NEWS_TAX_REWRITE,
    NEWS_TAX: process.env.NEWS_TAX,
    CTF7_VI: process.env.CTF7_VI,
    CTF7_JA: process.env.CTF7_JA,
    TINTUC_VI: process.env.TINTUC_VI,
    TINTUC_JA: process.env.TINTUC_JA,
    HDXH_VI: process.env.HDXH_VI,
    HDXH_JA: process.env.HDXH_JA,
    VAN_HOA_DOI_SONG_VI: process.env.VAN_HOA_DOI_SONG_VI,
    VAN_HOA_DOI_SONG_JA: process.env.VAN_HOA_DOI_SONG_JA,
    PAGES_POST_TYPE: process.env.PAGES_POST_TYPE,
    HDXH_POST_TYPE: process.env.HDXH_POST_TYPE,
    TINH_TIEN_NENKINS_THUE_VI: process.env.TINH_TIEN_NENKINS_THUE_VI,
    TINH_TIEN_NENKINS_THUE_JA: process.env.TINH_TIEN_NENKINS_THUE_JA,
    TINH_TIEN_NENKINS_VI: process.env.TINH_TIEN_NENKINS_VI,
    TINH_TIEN_NENKINS_JA: process.env.TINH_TIEN_NENKINS_JA,
    TINH_TIEN_HOANTHUE_VI: process.env.TINH_TIEN_HOANTHUE_VI,
    TINH_TIEN_HOANTHUE_JA: process.env.TINH_TIEN_HOANTHUE_JA,
    MSALARY1: process.env.MSALARY1,
    MSALARY2: process.env.MSALARY2,
    MSALARY3: process.env.MSALARY3,
    TREN_70_TUOI_VALUE : process.env.TREN_70_TUOI_VALUE,
    DUOI_70_TUOI_VALUE : process.env.DUOI_70_TUOI_VALUE,
    TU_19_DEN_23_TUOI_VALUE : process.env.TU_19_DEN_23_TUOI_VALUE,
    NGOAI_19_DEN_23_TUOI_VALUE : process.env.NGOAI_19_DEN_23_TUOI_VALUE,
    YES_VALUE : process.env.YES_VALUE,
    NO_VALUE : process.env.NO_VALUE,
    HT_MIENTHUE_DEF1 : process.env.HT_MIENTHUE_DEF1,
    HT_MIENTHUE_DEF2 : process.env.HT_MIENTHUE_DEF2,
    HT_MIENTHUE_DEF3 : process.env.HT_MIENTHUE_DEF3,
    HT_MIENTHUE_DEF4 : process.env.HT_MIENTHUE_DEF4,
    HT_MIENTHUE_DEF5 : process.env.HT_MIENTHUE_DEF5,
    HT_MIENTHUE_DEF6 : process.env.HT_MIENTHUE_DEF6,
    HT_MIENTHUE_DEF7 : process.env.HT_MIENTHUE_DEF7,
    HT_MIENTHUE_DEF8 : process.env.HT_MIENTHUE_DEF8,
    DANG_NHAP_VI : process.env.DANG_NHAP_VI,
    DANG_NHAP_JA : process.env.DANG_NHAP_JA,
    DANG_KY_VI : process.env.DANG_KY_VI,
    DANG_KY_JA : process.env.DANG_KY_JA,
    QUEN_MAT_KHAU_VI : process.env.QUEN_MAT_KHAU_VI,
    QUEN_MAT_KHAU_JA : process.env.QUEN_MAT_KHAU_JA,
    RESET_MAT_KHAU_VI : process.env.RESET_MAT_KHAU_VI,
    RESET_MAT_KHAU_JA : process.env.RESET_MAT_KHAU_JA,
    CONFIRM_NENKINS_NO2_VI : process.env.CONFIRM_NENKINS_NO2_VI,
    CONFIRM_NENKINS_NO2_JA : process.env.CONFIRM_NENKINS_NO2_JA,
    //
    ACCOUNT_VI : process.env.ACCOUNT_VI,
    ACCOUNT_JA : process.env.ACCOUNT_JA,    
    ACCOUNT_THONGTINTAIKHOAN_VI : process.env.ACCOUNT_THONGTINTAIKHOAN_VI,
    ACCOUNT_THONGTINTAIKHOAN_JA : process.env.ACCOUNT_THONGTINTAIKHOAN_JA,
    ACCOUNT_CAPNHATHSNENKIN_VI : process.env.ACCOUNT_CAPNHATHSNENKIN_VI,
    ACCOUNT_CAPNHATHSNENKIN_JA : process.env.ACCOUNT_CAPNHATHSNENKIN_JA,
    ACCOUNT_CAPNHATHSHOANTHUE_VI : process.env.ACCOUNT_CAPNHATHSHOANTHUE_VI,
    ACCOUNT_CAPNHATHSHOANTHUE_JA : process.env.ACCOUNT_CAPNHATHSHOANTHUE_JA,
    ACCOUNT_KIEMTRATIENDO_VI : process.env.ACCOUNT_KIEMTRATIENDO_VI,
    ACCOUNT_KIEMTRATIENDO_JA : process.env.ACCOUNT_KIEMTRATIENDO_JA,
    ACCOUNT_DOIMATKHAU_VI : process.env.ACCOUNT_DOIMATKHAU_VI,
    ACCOUNT_DOIMATKHAU_JA : process.env.ACCOUNT_DOIMATKHAU_JA,
    ACCOUNT_XULYHS_VI : process.env.ACCOUNT_XULYHS_VI,
    ACCOUNT_XULYHS_JA : process.env.ACCOUNT_XULYHS_JA,
    //
    SEARCH_VI : process.env.SEARCH_VI,
    SEARCH_JA : process.env.SEARCH_JA,
    //
    NEXTAUTH_URL : process.env.NEXTAUTH_URL,
    SECRET : process.env.SECRET,
    FACEBOOK_ID : process.env.FACEBOOK_ID,
    FACEBOOK_SECRET : process.env.FACEBOOK_SECRET,
    //
    VERIFIED_KEY : process.env.VERIFIED_KEY,
    CONFIRMED_NENKIN_KEY : process.env.CONFIRMED_NENKIN_KEY,
    ENDING_REPORTER_FLAG_KEY : process.env.ENDING_REPORTER_FLAG_KEY,
    //
    E_REGISTER_CODE : process.env.E_REGISTER_CODE,
    E_UPDATE_CODE : process.env.E_UPDATE_CODE,
    E_CHECK_TO_NENKIN_CODE : process.env.E_CHECK_TO_NENKIN_CODE,
    E_DENY_REPORTER_CODE : process.env.E_DENY_REPORTER_CODE,
    E_NENKIN_RESULTS_NO1_CODE : process.env.E_NENKIN_RESULTS_NO1_CODE,
    E_NENKIN_CONFIRM_NO1_CODE : process.env.E_NENKIN_CONFIRM_NO1_CODE,
    E_NENKIN_RESULTS_NO2_CODE : process.env.E_NENKIN_RESULTS_NO2_CODE,
    E_NENKIN_CONFIRM_NO2_CODE : process.env.E_NENKIN_CONFIRM_NO2_CODE,
    E_NENKIN_FINISH_REFUND_NO3_CODE : process.env.E_NENKIN_FINISH_REFUND_NO3_CODE,
    E_NENKIN_CONFIRM_NO3_CODE : process.env.E_NENKIN_CONFIRM_NO3_CODE,
    E_ENDING_REPORTER_CODE : process.env.E_ENDING_REPORTER_CODE,
  }, // rebuild
}
